name: "Nix Build Rust Sega"
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v27

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          # Optional: use a binary cache for faster builds
          extra-nix-config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/

      - name: Build Rust Sega with Nix
        run: |
              cd rust_rustsega
              nix build .

